Fields["btn_displayReport"].click();
Wait.forMilliseconds(500);
Fields["btn_displayRecord"].click();
Wait.forMilliseconds(500);
Fields["btn_cancelRecord"].click();
Wait.forMilliseconds(500);
Window.sendKeys("j");
Window.sendKeys("j");
Fields["btn_displayReport"].click();
