Debug.showDialog("Dialog #1");
Fields['Forside-link'].click();
//Debug.showDialog("Dialog #2");
Fields['Selvbetjening Link på politi.dk'].click();
//Debug.showDialog("Dialog #3");
Fields['Forside-link'].click();
//Debug.showDialog("Dialog #4");
Fields['Skift til engelsk klik'].click();
//Debug.showDialog("Dialog #5");
Fields['Skift til dansk fra engelsk'].click();
Fields['Forside-link'].click();
Debug.showDialog("Dialog #6");
Fields['Søgefelt'].input("Fartbøller");
//Debug.showDialog("Dialog #7");
Fields['Søgeknap'].click();
Debug.showDialog("Dialog #8");
